apiVersion: v1
kind: Service
metadata:
  name: gursewakq2app
  labels:
    app: gursewakq2app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30040
    targetPort: 80
    protocol: TCP
  selector:
    app: gursewakq2app


